version: "3.9"

services:
    php-apache:
        container_name: php-apache-laravel-practice
        ports:
            - '8080:80'
        build:
            context: ./
        volumes:
            - ./:/var/www/html
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - mysql
    mysql:
        image: mysql:8.0.28
        platform: linux/amd64
        container_name: mysql-laravel-practice
        ports:
            - "6033:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_practice
            TZ: "Asia/Tokyo"
        volumes:
            - data-volume:/var/lib/mysql

volumes:
    data-volume:
